### PR TITLE
Incremented version to 1.3.4.

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
Increment version to 1.3.4 
 
### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saikaranam-amazon** [comment]
we are dependent on common-utils and building is failing as artifacts are not yet published for 1.3.4
```
Could not determine the dependencies of task ':thirdPartyAudit'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve org.opensearch:common-utils:1.3.4.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.opensearch:common-utils:1.3.4.0-SNAPSHOT.
         > Could not get resource 'https://plugins.gradle.org/m2/org/opensearch/common-utils/1.3.4.0-SNAPSHOT/common-utils-1.3.4.0-SNAPSHOT.pom'.
            > Could not GET 'https://repo.gradle.org/artifactory/jcenter/org/opensearch/common-utils/1.3.4.0-SNAPSHOT/common-utils-1.3.4.0-SNAPSHOT.pom'. Received status code 409 from server: Conflict

```

**Comment by zelinh** [comment]
We should be having the common-utils snapshot now. Please help re-run the checks. Thanks.

**Comment by saikaranam-amazon** [comment]
Security tests are failing as security plugin is not loading: 

```
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.78.Final.jar:4.1.78.Final]
»  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.78.Final.jar:4.1.78.Final]
»  	at java.lang.Thread.run(Thread.java:829) [?:?]
» ERROR][o.o.ExceptionsHelper     ] [leaderCluster-0] fatal error
»  	at org.opensearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:310)
»  	at java.base/java.util.Optional.ifPresent(Optional.java:183)
»  	at org.opensearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:300)
»  	at org.opensearch.http.netty4.Netty4HttpServerTransport$HttpChannelHandler.exceptionCaught(Netty4HttpServerTransport.java:368)
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
»  	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
»  	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
»  	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
»  	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:627)
»  	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:181)
»  	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:152)
»  	at org.opensearch.security.ssl.http.netty.SecuritySSLNettyHttpServerTransport$SSLHttpChannelHandler.initChannel(SecuritySSLNettyHttpServerTransport.java:84)
»  	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
»  	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
»  	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
»  	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
»  	at io.netty.channel.
```

**Review by saikaranam-amazon — APPROVED** [review]

**Review by ankitkala — APPROVED** [review]

**Comment by saikaranam-amazon** [comment]
security plugin load issue tracked in : https://github.com/opensearch-project/security/issues/1934

**Pull request merged**
