### PR TITLE
added groupId to pluginzip publication

### LINKED ISSUE #534: [ENHANCEMENT] opensearch.opensearchplugin add groupID field to org.opensearch.plugin
### Description

The configuration modification for the gradle plugin `opensearch.pluginzip` to make sure the `groupId` is added as `org.opensearch.plugin` to the publication `pluginZip` inside the `build.gradle` file.

### Related META issue

Part of: https://github.com/opensearch-project/opensearch-build/issues/2521
From solution: https://github.com/opensearch-project/OpenSearch/issues/3692

### Current Behavior

The `opensearch.opensearchplugin` uses the default setting for `groupId` as `org.opensearch.plugin`, this when extended with open source community, it should be feasible to ammend the `groupId` as per required, hence for opensearch plugins the `groupId` should be mentioned as `org.opensearch.plugin` to make sure the opensearch plugins are published to this `groupID` and for other generic uses this can be extended to the custom `groupId`.

### Expected Behavior

Once the `groupId` is added as `org.opensearch.plugin` to the publication `pluginZip` inside the `build.gradle` file, the plugin zips should continue to be published to the existing `groupID`.

### Proposed solution

Solution from the PR: https://github.com/opensearch-project/OpenSearch/issues/3692

### PR DESCRIPTION
**Pull request by sricharanvuppu**
Signed-off-by: sricharanvuppu <srivuppu@amazon.com>

### Description
Added `groupId` as `org.opensearch.plugin` in `pluginZip` publication
 
### Issues Resolved
#534 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ankitkala** [comment]
LGTM. Let's wait for confirmation from @prudhvigodithi incase anything else is required.

**Comment by prudhvigodithi** [comment]
Looks good, but should be back-ported to 2.x only during 2.4 release else the build would break.
related PR https://github.com/opensearch-project/OpenSearch/pull/4360 
CC @lukas-vlcek

**Review by ankitkala — APPROVED** [review]

**Comment by sricharanvuppu** [comment]
@prudhvigodithi  Can we merge this to main

**Comment by prudhvigodithi** [comment]
Hey @sricharanvuppu, yes we can merge this PR, but lets not backport it to 2.x I would suggest to just wait until the following PR is backported to 2.x from core, else the distribution build would fail compiling cross-cluster-replication for 2.4 version. @bbarani @lukas-vlcek @dblock 
https://github.com/opensearch-project/OpenSearch/pull/4360#issuecomment-1260454721
Thank you

**Pull request merged**
