### PR TITLE
Incremented version to 1.2.4.

### PR DESCRIPTION
**Pull request by dblock**
Coming from https://github.com/opensearch-project/opensearch-build/issues/1417.

### CODE REVIEW

**Comment by dblock** [comment]
Not sure how to fix CI here.

**Review by saikaranam-amazon — APPROVED** [review]

**Review by ankitkala — APPROVED** [review]

**Comment by dblock** [comment]
This got merged with failing CI?

**Comment by saikaranam-amazon** [comment]
> This got merged with failing CI?

There is one flaky test that is failing CI unrelated to these changes.  I am debugging the issue and will merge the changes to 1.2.4 branch.

**Comment by dblock** [comment]
> > This got merged with failing CI?
> 
> There is one flaky test that is failing CI unrelated to these changes. I am debugging the issue and will merge the changes to 1.2.4 branch.

Is there an issue #? Add to https://github.com/opensearch-project/cross-cluster-replication/issues/279?

**Comment by saikaranam-amazon** [comment]
Tracking in https://github.com/opensearch-project/cross-cluster-replication/issues/280

**Pull request merged**
