### PR TITLE
Publish CCR zip to maven repo

### PR DESCRIPTION
**Pull request by ankitkala**
Signed-off-by: Ankit Kala <ankikala@amazon.com>

### Description
Publish CCR zip to maven repo
 
Depends on https://github.com/opensearch-project/cross-cluster-replication/pull/398/files

### Issues Resolved
https://github.com/opensearch-project/cross-cluster-replication/issues/384
 
###Testing done.
Verifed the zips in `build/local-staging-repo/org/opensearch/plugin/opensearch-cross-cluster-replication`
```
88665a0f606e:cross-cluster-replication ankikala$ ls build/local-staging-repo/org/opensearch/plugin/opensearch-cross-cluster-replication/2.0.0.0-SNAPSHOT/
maven-metadata.xml
maven-metadata.xml.md5
maven-metadata.xml.sha1
maven-metadata.xml.sha256
maven-metadata.xml.sha512
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.pom
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.pom.md5
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.pom.sha1
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.pom.sha256
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.pom.sha512
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.zip
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.zip.md5
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.zip.sha1
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.zip.sha256
opensearch-cross-cluster-replication-2.0.0.0-20220517.115038-1.zip.sha512
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.pom
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.pom.md5
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.pom.sha1
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.pom.sha256
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.pom.sha512
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.zip
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.zip.md5
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.zip.sha1
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.zip.sha256
opensearch-cross-cluster-replication-2.0.0.0-20220517.115758-2.zip.sha512
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.pom
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.pom.md5
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.pom.sha1
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.pom.sha256
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.pom.sha512
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.zip
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.zip.md5
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.zip.sha1
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.zip.sha256
opensearch-cross-cluster-replication-2.0.0.0-20220517.121842-3.zip.sha512
```

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ankitkala** [comment]
This PR has a dependency on https://github.com/opensearch-project/cross-cluster-replication/pull/398/files

**Comment by ankitkala** [comment]
> Hey @ankitkala, please verify the published zips have right POM coordinates, you should be adding
> 
> ```
>     publications {
>         pluginZip(MavenPublication) { publication ->
>             pom {
>                 name = opensearchplugin.name
>                 description = opensearchplugin.description
>                 licenses {
>                     license {
>                         name = "The Apache License, Version 2.0"
>                         url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
>                     }
>                 }
>                 developers {
>                     developer {
>                         name = "OpenSearch"
>                         url = "https://github.com/opensearch-project/cross-cluster-replication"
>                     }
>                 }
>             }
>         }
>     }
> }
> ```
> 
> Example PR: [opensearch-project/index-management#366](https://github.com/opensearch-project/index-management/pull/366)

The build fails as the publishing `pluginZip` already exists. 
```
Cannot add a Publication with name 'pluginZip' as a Publication with that name already exists.
```

I tried changing the publication name but it again failed with 
```
> Task :validatePluginZipCCRPom FAILED
Execution optimizations have been disabled for task ':validatePluginZipCCRPom' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Volumes/ws/cross-cluster-replication/build/distributions/opensearch-cross-cluster-replication-2.0.0.0-rc1-SNAPSHOT.pom'. Reason: Task ':validatePluginZipCCRPom' uses this output of task ':generatePomFileForNebulaPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
description is missing in [/Volumes/ws/cross-cluster-replication/build/distributions/opensearch-cross-cluster-replication-2.0.0.0-rc1-SNAPSHOT.pom]
```

**Comment by ankitkala** [comment]
Also, do we need to add custom POM extension? Can't the `opensearch.pluginzip` infer the `name`,`description`,`license`,etc by itself?

**Comment by prudhvigodithi** [comment]
This could be the issue https://github.com/opensearch-project/cross-cluster-replication/blob/main/build.gradle#L39 can you try with `2.0.1-SNAPSHOT` ?

**Review by soosinha — APPROVED** [review]

**Review by saikaranam-amazon — APPROVED** [review]

**Pull request merged**
