### PR TITLE
Incremented version to 2.1.1.

### PR DESCRIPTION
**Pull request by gaiksaya**
Coming from https://github.com/opensearch-project/opensearch-build/issues/1818 post release activities.

### CODE REVIEW

**Comment by ankitkala** [comment]
Security plugin has to be upgraded and built before this PR can be merged.

**Comment by gaiksaya** [comment]
> Security plugin has to be upgraded and built before this PR can be merged.

Security plugin has been upgraded

**Comment by ankitkala** [comment]
> > > Security plugin has to be upgraded and built before this PR can be merged.
> > 
> > 
> > Security plugin has been upgraded [opensearch-project/security#1939](https://github.com/opensearch-project/security/pull/1939)
> 
> It also needs to be built as part of distribution build so that we can fetch the plugin snapshot zip. Here is the PR for the change: [opensearch-project/opensearch-build#2349](https://github.com/opensearch-project/opensearch-build/pull/2349)

This has been merged. @gaiksaya Can you rebase your changes once? After rebase the workflow should be able to fetch the security plugin zip for `2.1.1` and test will succeed.

**Comment by gaiksaya** [comment]
Hi @ankitkala Looks like security plugin was added yesterday and we have stopped builds due to jenkins migration. Will rerun this once builds are back on.
Thanks!

**Comment by gaiksaya** [comment]
Hi @ankitkala Looks like test and build workflow is still failing. 

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':integTest'.
> There were failing tests. See the report at: file:///home/runner/work/cross-cluster-replication/cross-cluster-replication/build/reports/tests/integTest/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
```

**Review by ankitkala — APPROVED** [review]

**Review by saikaranam-amazon — APPROVED** [review]

**Pull request merged**
