### PR TITLE
Added validations for indexPattern in autofollow API

### PR DESCRIPTION
**Pull request by skumarp7**
### Description

Opening a new PR since old PR got closed by mistake. 

This PR adds validations for the indexPattern configured in autofollow API
 
 Existing behavior of the autofollow API with invalid indexPattern: 
 
```
  curl -Method POST -Uri "http://localhost:9201/_plugins/_replication/_autofollow?pretty"  -H @{'Content-Typ
e' = 'application/json'} -body '{"leader_alias":"leader", "name": "test", "pattern": "test/abcd"}'                   


StatusCode        : 200
StatusDescription : OK
Content           : {
                      "acknowledged" : true
                    }
```

 
 Behaviour after adding validations on indexPattern: 
 
```
curl -Method POST -Uri "http://localhost:9201/_plugins/_replication/_autofollow?pretty"  -H @{'Content-Typ
e' = 'application/json'} -body '{"leader_alias":"leader_sanjay", "name": "test", "pattern": "test/adfas"}'

curl : { "error" : { "root_cause" : [ { "type" : "action_request_validation_exception", "reason" : "Validation Failed: 1: Autofollow pattern: 
test/adfas must not contain the following characters [ , \", *, \\, <, |, ,, >, /, ?];" } ], "type" : "action_request_validation_exception", 
"reason" : "Validation Failed: 1: Autofollow pattern: test/adfas must not contain the following characters [ , \", *, \\, <, |, ,, >, /, ?];" },    
"status" : 400 }
```

 
### Issues Resolved
https://github.com/opensearch-project/cross-cluster-replication/issues/1034
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by skumarp7** [comment]
Hi @monusingh-1 

Can you help me here with the test failures? i dont see any test failures in my local

**Comment by monusingh-1** [comment]
Restarted failed workflow

**Comment by skumarp7** [comment]
Hi @monusingh-1 @ankitkala , 

Any update on this PR?

**Comment by skumarp7** [comment]
Hi @ankitkala & @monusingh-1 , 

I tried spending some time on the failures on this PR. I had run the same failing tests in my local with security enabled, i couldnt reproduce the failed tests in the CI. Can we try to retrigger the tests ?

**Comment by ankitkala** [comment]
> Hi @ankitkala & @monusingh-1 ,
> 
> I tried spending some time on the failures on this PR. I had run the same failing tests in my local with security enabled, i couldnt reproduce the failed tests in the CI. Can we try to retrigger the tests ?

Somehow i'm not getting an option to restart the workflow. Can you push an empty commit on your branch, that should trigger the tests.

**Comment by skumarp7** [comment]
> > Hi @ankitkala & @monusingh-1 ,
> > I tried spending some time on the failures on this PR. I had run the same failing tests in my local with security enabled, i couldnt reproduce the failed tests in the CI. Can we try to retrigger the tests ?
> 
> Somehow i'm not getting an option to restart the workflow. Can you push an empty commit on your branch, that should trigger the tests.

done

**Review by ankitkala — APPROVED** [review]

**Review by monusingh-1 — APPROVED** [review]

**Pull request merged**
