### PR TITLE
Changes to support replication plugin on OpenSearch v2.2.0

### PR DESCRIPTION
**Pull request by saikaranam-amazon**
### Description
Changes to support replication plugin on OpenSearch v2.2.0

- Updated the CI link to force on #5858 (to fetch the security plugin) and unblock the release - https://github.com/opensearch-project/cross-cluster-replication/issues/472
 
### Issues Resolved
https://github.com/opensearch-project/cross-cluster-replication/issues/462
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saikaranam-amazon** [comment]
Security tests are failing as release artifacts are not available

```
Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.2.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-2.2.0.0.zip to /home/runner/work/cross-cluster-replication/cross-cluster-replication/build/dependencies/security/opensearch-security-2.2.0.0.zip
```

**Comment by saikaranam-amazon** [comment]
> Security tests are failing as release artifacts are not available
```
Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.2.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-2.2.0.0.zip to /home/runner/work/cross-cluster-replication/cross-cluster-replication/build/dependencies/security/opensearch-security-2.2.0.0.zip
```
@prudhvigodithi Are we not publishing pre-release artifacts under the above repo, once they are part of the manifest?

**Comment by saikaranam-amazon** [comment]
Security plugin build is failing due to compilation issue
```
/home/runner/work/cross-cluster-replication/cross-cluster-replication/security/src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java:920: error: <anonymous org.opensearch.security.configuration.DlsFlsFilterLeafReader$4> is not abstract and does not override abstract method docValueCount() in SortedSetDocValues
                return new SortedSetDocValues() {
                                                ^
/home/runner/work/cross-cluster-replication/cross-cluster-replication/security/src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java:968: error: docValueCount() in <anonymous org.opensearch.security.configuration.DlsFlsFilterLeafReader$4> cannot override docValueCount() in SortedSetDocValues
> Task :compileJava
                    public long docValueCount() {
                                ^
  return type long is not compatible with int
/home/runner/work/cross-cluster-replication/cross-cluster-replication/security/src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java:967: error: method does not override or implement a method from a supertype
                    @Override
                    ^
```

**Comment by prudhvigodithi** [comment]
Hey @saikaranam-amazon I see with 2.2.0 the distribution build did not pass with security plugin, hence you are not able to access the zip.
https://build.ci.opensearch.org/job/distribution-build-opensearch/5855/
@peterzhuamazon @bbarani

**Review by soosinha — APPROVED** [review]

**Review by ankitkala — APPROVED** [review]
Let's also open the PR to update the security plugin path to `latest` and link it here for reference.

**Pull request merged**
